# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: afulmini <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/24 13:17:14 by afulmini          #+#    #+#              #
#    Updated: 2020/02/25 15:07:07 by afulmini         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

OUT = libft.a
SRC = srcs/

CC = gcc 
CCFLAGS = -Wall -Wextra -Werror

.PHONY: clean
clean :
		

.PHONY: fclean
fclean : clean

